title: 'Globals SEO: Page Meta - Environments'
fields:
  -
    handle: noindex_local
    field:
      type: toggle
      instructions_position: below
      listable: false
      display: Local
      width: 33
      localizable: true
  -
    handle: noindex_staging
    field:
      type: toggle
      instructions_position: below
      listable: false
      display: Staging
      width: 33
      localizable: true
  -
    handle: noindex_production
    field:
      type: toggle
      instructions_position: below
      listable: false
      display: Production
      width: 33
      localizable: true
